FROM node:16.15

WORKDIR /app

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY package*.json ./
COPY ./ .
RUN npm install

ENTRYPOINT ["/entrypoint.sh"]

CMD ["npm", "run", "preview"]