version: 2.1
orbs:
  docker: circleci/docker@2.1.2
  k8s: digitalocean/k8s@0.1.1
jobs:
  build-and-push:
    executor: docker/machine
    steps:
      - checkout
      - docker/check
      - docker/build:
          # deploy: false
          dockerfile: Dockerfile-K8S
          image: smlsoft/vfgl
          #use-docker-credentials-store: true
          tag: dev
      - docker/push:
          image: smlsoft/vfgl
          tag: dev
          
  deploy-dev:
    executor: docker/machine
    steps:
      - checkout
      - k8s/install
      - k8s/initialize:
          cluster: 916a438e-9629-4798-8a7e-c5e31acb5b99
      - run: kubectl rollout restart deployment/vfgl-dev-webapp -n dedepos-dev
  build-releases-and-push:
    executor: docker/machine
    steps:
      - checkout
      - docker/check
      - docker/build:
          # deploy: false
          dockerfile: Dockerfile-K8S
          image: smlsoft/vfgl
          #use-docker-credentials-store: true
          tag: releases
      - docker/push:
          image: smlsoft/vfgl
          tag: releases
          
  deploy-releases:
    executor: docker/machine
    steps:
      - checkout
      - k8s/install
      - k8s/initialize:
          cluster: 916a438e-9629-4798-8a7e-c5e31acb5b99
      - run: kubectl rollout restart deployment/vfgl-prd-webapp -n dedepos-prd
  
workflows:
  build-dev-only:
    jobs:
      - build-and-push:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - develop
      - deploy-dev:
          requires:
            - build-and-push
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - develop
  build-releases:
    jobs:
      - build-releases-and-push:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - releases
      - deploy-releases:
          requires:
            - build-releases-and-push
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - releases