apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vfadmin-uat-dedepos-com-cluster-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: toe@smlsoft.com
    privateKeySecretRef:
      name: vfadmin-uat-dedepos-com-tls-secert
    solvers:
      - http01:
          ingress:
            class: nginx